import React from 'react'
import { Button } from './button'
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by Figma Code Connect --
 */

figma.connect(Button, 'https://www.figma.com/design/example-file-id/example-name?node-id=0-1', {
  props: {
    variant: figma.enum('Variant', {
      Primary: 'default',
      Secondary: 'secondary',
      Destructive: 'destructive',
      Outline: 'outline',
      Ghost: 'ghost',
      Link: 'link',
    }),
    size: figma.enum('Size', {
      Default: 'default',
      Small: 'sm',
      Large: 'lg',
      Icon: 'icon',
    }),
    label: figma.textContent('Label'),
  },
  example: ({ label, variant, size }) => (
    <Button variant={variant} size={size}>
      {label}
    </Button>
  ),
})
